name: app_movil_pdam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.9.2
  flutter_secure_storage: ^10.3.1
  auto_size_text: ^3.0.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  go_router: ^17.3.0
  image_picker: ^1.0.7
  mobile_scanner: ^5.2.0 
  permission_handler: ^11.3.1


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imgs/
    - assets/icos/
  
